# Generated by Django 3.0 on 2021-11-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0030_auto_20211014_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesArrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOFArrows', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.FinicialCompany')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.SeniorOwner')),
            ],
        ),
    ]
