# Generated by Django 3.0 on 2021-11-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
