# Generated by Django 3.0 on 2021-12-24 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0030_auto_20211014_1138'),
        ('owners', '0004_auto_20211225_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesarrow',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners_arrow', to='office.FinicialCompany'),
        ),
        migrations.AlterField(
            model_name='companiesarrow',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_related', to='owners.SeniorOwner'),
        ),
    ]
