# Generated by Django 3.0 on 2021-12-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0032_auto_20211229_1402'),
        ('owners', '0005_auto_20211225_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinicalCompaniesArrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOFArrows', models.IntegerField(blank=True, null=True)),
                ('ownRatio', models.FloatField(blank=True, null=True)),
                ('arrowPrice', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_owned', to='office.FinicialCompany')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_that_owned', to='office.FinicialCompany')),
            ],
        ),
    ]
