# Generated by Django 3.0 on 2022-01-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0006_finicalcompaniesarrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='companiesarrow',
            name='totalOwnRatioToday',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companiesarrow',
            name='totalOwnRatioYesterday',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
