# Generated by Django 3.0 on 2022-02-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0007_auto_20220108_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companiesarrow',
            name='arrowPrice',
        ),
        migrations.RemoveField(
            model_name='companiesarrow',
            name='numberOFArrows',
        ),
        migrations.RemoveField(
            model_name='finicalcompaniesarrow',
            name='arrowPrice',
        ),
    ]
