# Generated by Django 3.0 on 2022-02-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0008_auto_20220201_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='companiesarrow',
            name='total_arrows_owned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
