# Generated by Django 3.0 on 2022-02-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0009_companiesarrow_total_arrows_owned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesarrow',
            name='total_arrows_owned',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
