# Generated by Django 3.0 on 2022-02-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0012_auto_20220208_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesarrow',
            name='ownRatio',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='companiesarrow',
            name='totalOwnRatioToday',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='companiesarrow',
            name='totalOwnRatioYesterday',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='companiesarrow',
            name='total_arrows_owned',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='finicalcompaniesarrow',
            name='numberOFArrows',
            field=models.BigIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='finicalcompaniesarrow',
            name='ownRatio',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
