# Generated by Django 3.0 on 2022-02-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0013_auto_20220208_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finicalcompaniesarrow',
            name='numberOFArrows',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
