# Generated by Django 3.0 on 2022-02-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0043_auto_20220221_1951'),
        ('owners', '0014_auto_20220210_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesarrow',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners_arrow', to='office.FinicialCompany'),
        ),
        migrations.AlterField(
            model_name='companiesarrow',
            name='ownRatio',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='companiesarrow',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies_related', to='owners.SeniorOwner'),
        ),
        migrations.AlterField(
            model_name='companiesarrow',
            name='totalOwnRatioToday',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='companiesarrow',
            name='totalOwnRatioYesterday',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='companiesarrow',
            name='total_arrows_owned',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='finicalcompaniesarrow',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_owned', to='office.FinicialCompany'),
        ),
        migrations.AlterField(
            model_name='finicalcompaniesarrow',
            name='numberOFArrows',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='finicalcompaniesarrow',
            name='ownRatio',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='finicalcompaniesarrow',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_that_owned', to='office.FinicialCompany'),
        ),
    ]
