# Generated by Django 3.0 on 2022-02-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0015_auto_20220221_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='companiesarrow',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companiesarrow',
            name='owner_type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
