# Generated by Django 3.0 on 2022-02-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0016_auto_20220227_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesarrow',
            name='owner_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'فرد'), (2, 'شركة'), (3, 'مؤسسة حكومية')], null=True),
        ),
    ]
