# Generated by Django 3.0 on 2022-02-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_header', models.CharField(blank=True, max_length=255, null=True)),
                ('second_header', models.CharField(blank=True, max_length=255, null=True)),
                ('third_header', models.CharField(blank=True, max_length=255, null=True)),
                ('fourth_header', models.CharField(blank=True, max_length=255, null=True)),
                ('fifth_header', models.CharField(blank=True, max_length=255, null=True)),
                ('sixth_header', models.CharField(blank=True, max_length=255, null=True)),
                ('seventh_header', models.CharField(blank=True, max_length=255, null=True)),
                ('eight_header', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Earning Expectation',
            },
        ),
    ]
