# Generated by Django 3.0 on 2022-02-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteConfiguration',
            new_name='EarningHeader',
        ),
    ]
