# Generated by Django 3.0 on 2022-02-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220227_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningheader',
            name='nine_header',
            field=models.CharField(blank=True, help_text='Text for Real Earn', max_length=255, null=True),
        ),
    ]
