# Generated by Django 3.0 on 2022-02-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_earningheader_nine_header'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earningheader',
            options={},
        ),
    ]
