# Generated by Django 3.0 on 2022-02-27 22:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220228_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningheader',
            name='eight_header',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='fifth_header',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='first_header',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='fourth_header',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='nine_header',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='second_header',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='seventh_header',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='sixth_header',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='third_header',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
