# Generated by Django 3.0 on 2022-03-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220228_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningheader',
            name='eight_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='fifth_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='first_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='fourth_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='nine_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='second_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='seventh_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='sixth_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='earningheader',
            name='third_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
