# Generated by Django 3.0 on 2022-03-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220302_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningHeaderSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_header', models.CharField(blank=True, max_length=255, null=True)),
                ('second_header', models.CharField(blank=True, max_length=255, null=True)),
                ('third_header', models.CharField(blank=True, max_length=255, null=True)),
                ('fourth_header', models.CharField(blank=True, max_length=255, null=True)),
                ('fifth_header', models.CharField(blank=True, max_length=255, null=True)),
                ('sixth_header', models.CharField(blank=True, max_length=255, null=True)),
                ('seventh_header', models.CharField(blank=True, max_length=255, null=True)),
                ('eight_header', models.CharField(blank=True, max_length=255, null=True)),
                ('nine_header', models.CharField(blank=True, max_length=255, null=True)),
                ('tenth_header', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='earningheader',
            name='nine_header',
        ),
    ]
