# Generated by Django 3.0 on 2021-08-19 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyEntered', models.CharField(blank=True, max_length=255, null=True)),
                ('ResearchCompany', models.CharField(blank=True, max_length=255, null=True)),
                ('AnalayticName', models.CharField(blank=True, max_length=255, null=True)),
                ('Recommendation', models.CharField(blank=True, max_length=255, null=True)),
                ('FairValue', models.FloatField(blank=True, null=True)),
                ('CurrenncyValue', models.FloatField(blank=True, null=True)),
                ('MarketValue', models.FloatField(blank=True, null=True)),
                ('RecommendDate', models.DateField(auto_now_add=True)),
                ('report', models.FileField(upload_to='reportspdf/')),
                ('EmpEntered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
