# Generated by Django 3.0 on 2021-08-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finicialanalyst',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
