# Generated by Django 3.0 on 2021-08-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_researchcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='ResearchCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ResearchCompany', to='office.ResearchCompany'),
        ),
    ]
