# Generated by Django 3.0 on 2021-08-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_auto_20210829_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finicialanalyst',
            name='currentCompany',
        ),
        migrations.AddField(
            model_name='finicialanalyst',
            name='currentCompany',
            field=models.ManyToManyField(null=True, related_name='currentCompany', to='office.FinicialCompany'),
        ),
    ]
