# Generated by Django 3.0 on 2021-08-31 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20210831_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finicialanalyst',
            name='currentCompany',
        ),
        migrations.AddField(
            model_name='finicialanalyst',
            name='currentCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentCompany', to='office.FinicialCompany'),
        ),
        migrations.RemoveField(
            model_name='finicialanalyst',
            name='pervCompany',
        ),
        migrations.AddField(
            model_name='finicialanalyst',
            name='pervCompany',
            field=models.ManyToManyField(null=True, related_name='pervCompany', to='office.FinicialCompany'),
        ),
    ]
