# Generated by Django 3.0 on 2021-08-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_auto_20210831_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finicialanalyst',
            options={'ordering': ['id'], 'verbose_name_plural': 'Analysts'},
        ),
    ]
