# Generated by Django 3.0 on 2021-09-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_auto_20210831_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerviousCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.FinicialAnalyst')),
            ],
        ),
    ]
