# Generated by Django 3.0 on 2021-09-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0010_perviouscompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finicialanalyst',
            name='pervCompany',
        ),
        migrations.RemoveField(
            model_name='finicialanalyst',
            name='pervJob',
        ),
    ]
