# Generated by Django 3.0 on 2021-09-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_auto_20210905_1649'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='finicialanalyst',
            index=models.Index(fields=['name', 'phone', 'tiwtterAccount', 'email'], name='office_fini_name_3c981f_idx'),
        ),
        migrations.AddIndex(
            model_name='perviouscompany',
            index=models.Index(fields=['job', 'analyst', 'company'], name='office_perv_job_4137a1_idx'),
        ),
        migrations.AddIndex(
            model_name='rates',
            index=models.Index(fields=['FairValue', 'AnalayticName', 'CompanyEntered'], name='office_rate_FairVal_8397e0_idx'),
        ),
        migrations.AddIndex(
            model_name='researchcompany',
            index=models.Index(fields=['name'], name='office_rese_name_398da4_idx'),
        ),
    ]
