# Generated by Django 3.0 on 2021-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0015_auto_20210908_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='finicialanalyst',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='finicialcompany',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
