# Generated by Django 3.0 on 2021-09-16 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import office.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office', '0018_auto_20210910_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(null=True, upload_to='reportspdf/')),
                ('ExpectRate', models.IntegerField(blank=True, null=True)),
                ('CompanyEntered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.FinicialCompany')),
                ('EmpEntered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ResearchCompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.ResearchCompany')),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office.FinicialAnalyst')),
            ],
        ),
        migrations.CreateModel(
            name='ExpectYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=office.models.current_year, null=True)),
                ('quaratar', models.CharField(choices=[('الربع الأول', 'الربع الأول'), ('الربع الثانى', 'الربع الثانى'), ('الربع الثالث', 'الربع الثالث'), ('الربع الرابع', 'الربع الرابع')], default='الربع الأول', max_length=255)),
                ('value', models.PositiveIntegerField(default=0, null=True)),
                ('expectYear', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office.EarningsForecast')),
            ],
        ),
        migrations.AddIndex(
            model_name='earningsforecast',
            index=models.Index(fields=['analyst'], name='office_earn_analyst_c7b241_idx'),
        ),
    ]
