# Generated by Django 3.0 on 2021-09-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0019_auto_20210916_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earningsforecast',
            name='ExpectRate',
        ),
        migrations.AddField(
            model_name='expectyear',
            name='ExpectRate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
