# Generated by Django 3.0 on 2021-09-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0020_auto_20210916_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expectyear',
            old_name='ExpectRate',
            new_name='ExpectPervYear',
        ),
        migrations.AddField(
            model_name='expectyear',
            name='ExpectthisYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
