# Generated by Django 3.0 on 2021-09-22 10:58

from django.db import migrations, models
import office.models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0021_auto_20210917_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=office.models.current_year, null=True)),
                ('quaratar', models.CharField(choices=[('الربع الأول', 'الربع الأول'), ('الربع الثانى', 'الربع الثانى'), ('الربع الثالث', 'الربع الثالث'), ('الربع الرابع', 'الربع الرابع')], default='الربع الأول', max_length=255)),
                ('value', models.PositiveIntegerField(default=0, null=True)),
                ('deviation_range', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ExpectYear',
        ),
        migrations.AddField(
            model_name='earningsforecast',
            name='expectYear',
            field=models.ManyToManyField(null=True, to='office.RateQuarter'),
        ),
    ]
