# Generated by Django 3.0 on 2021-09-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0023_earningsforecast_expectvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='change',
            field=models.BooleanField(null=True),
        ),
    ]
