# Generated by Django 3.0 on 2021-09-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0024_rates_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rates',
            old_name='change',
            new_name='changeFair',
        ),
        migrations.AddField(
            model_name='rates',
            name='changeMarket',
            field=models.BooleanField(null=True),
        ),
    ]
