# Generated by Django 3.0 on 2021-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0025_auto_20210928_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='Recommendation',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'زيادة الوزن'), (2, 'تخفيض الوزن'), (3, 'محايد')], max_length=255, null=True),
        ),
    ]
