# Generated by Django 3.0 on 2021-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0026_auto_20210928_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='finicialcompany',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
