# Generated by Django 3.0 on 2021-10-12 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0028_auto_20211005_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningsforecast',
            name='CompanyEntered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expects', to='office.FinicialCompany'),
        ),
    ]
