# Generated by Django 3.0 on 2021-10-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0029_auto_20211012_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningsforecast',
            name='ResearchCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Researchexpects', to='office.ResearchCompany'),
        ),
    ]
