# Generated by Django 3.0 on 2021-12-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0030_auto_20211014_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finicialcompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
