# Generated by Django 3.0 on 2022-01-25 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0032_auto_20211229_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=255, message='الأسم تعدى الحد المسموح بيه'), django.core.validators.MinValueValidator(limit_value=10, message='الأسم اقل الحد المسموح بيه')]),
        ),
        migrations.AlterField(
            model_name='researchcompany',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=255, message='الأسم تعدى الحد المسموح بيه'), django.core.validators.MinValueValidator(limit_value=10, message='الأسم اقل الحد المسموح بيه')]),
        ),
    ]
