# Generated by Django 3.0 on 2022-01-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0033_auto_20220125_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchcompany',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
