# Generated by Django 3.0 on 2022-01-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0034_auto_20220125_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finicialanalyst',
            name='currentCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currentCompany', to='office.ResearchCompany'),
        ),
    ]
