# Generated by Django 3.0 on 2022-02-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0036_auto_20220127_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='is_recommended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
