# Generated by Django 3.0 on 2022-02-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0037_rates_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningsforecast',
            name='is_recommended',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
