# Generated by Django 3.0 on 2022-02-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0038_earningsforecast_is_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='finicialcompany',
            name='arrow_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finicialcompany',
            name='total_arrows',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
