# Generated by Django 3.0 on 2022-02-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0039_auto_20220201_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finicialcompany',
            name='arrow_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
