# Generated by Django 3.0 on 2022-02-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0041_auto_20220210_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='changeFair',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='changeMarket',
        ),
    ]
