# Generated by Django 3.0 on 2022-02-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0043_auto_20220221_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningsforecast',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='office.FinicialAnalyst'),
        ),
    ]
