# Generated by Django 3.0 on 2022-03-06 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0045_auto_20220302_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectationYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_earn', models.FloatField(blank=True, null=True)),
                ('expect_earn', models.FloatField(blank=True, null=True)),
                ('quarter_now', models.FloatField(blank=True, null=True)),
                ('quarter_past', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='earningsforecast',
            name='first_quarter',
        ),
        migrations.RemoveField(
            model_name='earningsforecast',
            name='fourth_quarter',
        ),
        migrations.RemoveField(
            model_name='earningsforecast',
            name='realEarn',
        ),
        migrations.RemoveField(
            model_name='earningsforecast',
            name='second2020',
        ),
        migrations.RemoveField(
            model_name='earningsforecast',
            name='third2020',
        ),
        migrations.RemoveField(
            model_name='earningsforecast',
            name='total_earn',
        ),
        migrations.AddField(
            model_name='earningsforecast',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='office.ExpectationYear'),
        ),
    ]
