# Generated by Django 3.0 on 2022-03-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0046_auto_20220306_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningsforecast',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations', to='office.ExpectationYear'),
        ),
    ]
