# Generated by Django 3.0 on 2022-03-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0047_auto_20220306_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earningsforecast',
            name='year',
        ),
        migrations.AddField(
            model_name='expectationyear',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations', to='office.EarningsForecast'),
        ),
    ]
