# Generated by Django 3.0 on 2022-03-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0048_auto_20220306_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectationyear',
            name='is_show',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'الأرباح الفعلية/ التوقعات'), (2, 'التوقعات لأرباح الشركات')], null=True),
        ),
    ]
