# Generated by Django 3.0 on 2022-03-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0050_remove_expectationyear_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='Date_Entered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
