# Generated by Django 3.0 on 2022-03-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0051_rates_date_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningsforecast',
            name='expect_earn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsforecast',
            name='pervquarter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsforecast',
            name='quarter_past',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsforecast',
            name='real_earn',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
