from django.urls import path
from . import views

urlpatterns = [
    path('rates/list', views.RatesList, name='rates-list'),
    path('company/list', views.Company_List, name='company-list'),
    path('rates/<int:pk>', views.RateDetails, name='rate-details'),
    path('category/<int:pk>', views.CategoryDetails, name='category-details'),
    path('analyst/<int:pk>', views.AnalystDetails, name='analyst-details'),
    path('company/<int:pk>', views.CompanyDetails, name='company-details'),
    path('rates/update/<int:pk>', views.UpdateRate.as_view(), name='rate-update'),
    path('rates/add', views.AddRate.as_view(), name='rate-add'),
    path('expect/add', views.AddExpect.as_view(), name='expect-add'),
    path('expect/update/<int:pk>', views.UpdateExpect.as_view(), name='expect-update'),
    path('category/update/<int:pk>', views.UpdateCategory.as_view(), name='category-update'),
    path('research/update/<int:pk>', views.UpdateReserchCompany.as_view(), name='research-update'),
    path('company/update/<int:pk>', views.EditCompany.as_view(), name='company-update'),
    path('analyst/update/<int:pk>', views.UpdateAnalyst.as_view(), name='analyst-update'),
    path('analyst/add', views.AddAnalyst.as_view(), name='analyst-add'),
    path('company/add', views.AddCompany.as_view(), name='company-add'),
    path('research/add', views.AddReserchCompany.as_view(), name='research-add'),
    path('category/add', views.AddCategory.as_view(), name='category-add'),
    path('research/list', views.Research_List, name='research-list'),
    path('category/list', views.Category_List, name='category-list'),
    path('analayst/list', views.AnalystsList, name='analyst-list'),
    path('rates/report', views.RatesAllReport.as_view(), name='rates-report'),
    path('analysts/report', views.AnalystsAllReport.as_view(), name='analysts-report'),
    path('pervcompany/list/<int:pk>', views.PervCompanyList, name='pervcompany-list'),
    path('pervcompany/add/<int:pk>', views.addPervCompany, name='pervcompany-add'),
    path('expectations/list', views.ExpectationList, name='expectations-list'),
    path('code/update/<int:pk>', views.UpdateCode.as_view(), name='code-update'),
    path('code/add', views.AddCode.as_view(), name='code-add'),
    path('code/delete/<int:pk>', views.DeleteCompanyCode.as_view(), name='code-delete'),
    path('category/delete/<int:pk>', views.DeleteCompanyCategory.as_view(), name='category-delete'),
    path('company/delete/<int:pk>', views.DeleteFinicialCompany.as_view(), name='company-delete'),
    path('research/delete/<int:pk>', views.DeleteResearchCompany.as_view(), name='research-delete'),
    path('rates/delete/<int:pk>', views.DeleteRate.as_view(), name='rate-delete'),
    path('expect/delete/<int:pk>', views.DeleteEarningsForecast.as_view(), name='expect-delete'),
    path('analyst/delete/<int:pk>', views.DeleteFinicialAnalyst.as_view(), name='analyst-delete'),
    path('perv/delete/<int:pk>', views.DeletePervCompany.as_view(), name='perv-delete'),

]
